### ISSUE TITLE
Restricted rounds?

### ISSUE THREAD

**Issue by Junhojuno** [kennethwdk/LocLLM#2]
Hi:) first of all, Thank you for the nice work!

Reviewing the code, I found a curious point which is not explained in the paper.
in [coco.py](https://github.com/kennethwdk/LocLLM/blob/b33cb2f43ea7ed43606afb27dd04b0e44ceacae5/datasets/coco.py#L204-L207), it looks like round is restricted to five, but coco has 17 keypoints(rounds).
is there any reason using 5 rounds, not full rounds? 
```python      
 for idx in range(5):
      if idx >= len(kpt_des): break
      if self.conv_format == 'keypoint':
          q1 = "Where is the {} of this person in this image? Please provide its coordinates.".format(kpt_name[idx])
```

If there is anything that i misunderstood, please tell me! thanks😄

**Comment by Junhojuno** [comment]
I think, it results from VRAM issue. 5 keypoints' description is the maximum length of prompt in RTX 3090(24GB). because, if setting the description to much longer than COCO, the training script outputs "cuda-out-of-memory error".

**Comment by ni123die** [comment]
HI！Can you run the command bash scripts/valid_h36m.sh?
<img width="393" alt="image" src="https://github.com/user-attachments/assets/c7bec00f-4730-4dfe-abe4-5ed38c6b4814">

**Comment by PhucNDA** [comment]
Hi @Junhojuno,

Does this mean the results in the paper being benchmarked on only 5 COCO kpts from COCO Dataset? rather than 17 ?

**Comment by Junhojuno** [comment]
@PhucNDA sorry for late reply. This means not the result is benchmarked on only 5 COCO kpts, but is trained on the multi-round training which round is 5. I just wondered if there is any reason for the setting.
